Map<String, String> toShort = {
  // 'Croato' : 'hr',
  // 'Hrvatski' : 'hr',
  // 'Croate' : 'hr',
  // 'el Croata' : 'hr',
  // 'Croatian' : 'hr',
  // 'Kroatisch' : 'hr',

  // 'Inglese' : 'en',
  // 'Engleski' : 'en',
  // 'Anglais' : 'en',
  // 'el Inglés' : 'en',
  // 'English' : 'en',
  // 'Englisch' : 'en',

  // 'Spagnolo' : 'es',
  // 'Španjolski' : 'es',
  // 'Espagnol' : 'es',
  // 'el Español' : 'es',
  // 'Spanish' : 'es',
  // 'Spanisch' : 'es',

  // 'Francese' : 'fr',
  // 'Francuski' : 'fr',
  // 'Français' : 'fr',
  // 'el Francés' : 'fr',
  // 'French' : 'fr',
  // 'Französisch' : 'fr',

  // 'Tedesco' : 'de',
  // 'Njemački' : 'de',
  // 'Allemand' : 'de',
  // 'el Alemán' : 'de',
  // 'German' : 'de',
  // 'Deutsch' : 'de',

  // 'Italiano' : 'it',
  // 'Talijanski' : 'it',
  // 'Italien' : 'it',
  // 'el Italiano' : 'it',
  // 'Italian' : 'it',
  // 'Italienisch' : 'it',

  'Hrvatski' : 'hr',
  'English' : 'en',
  'Deutsch' : 'de',
  'Français' : 'fr',
  'Italiano' : 'it',
  'Español' : 'es'
};